// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.Models;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("server.Models.OperatorCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<double?>("Angle")
                        .HasColumnType("double precision")
                        .HasColumnName("angle");

                    b.Property<DateTime>("ExecutedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("IntervalValue")
                        .HasColumnType("integer")
                        .HasColumnName("interval_value");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("TurbineId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("turbine_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("operator_commands_pkey");

                    b.HasIndex(new[] { "TurbineId", "ExecutedAt" }, "idx_commands_turbine")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "UserId", "ExecutedAt" }, "idx_commands_user")
                        .IsDescending(false, true);

                    b.ToTable("operator_commands", (string)null);
                });

            modelBuilder.Entity("server.Models.Turbine", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("FarmId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("farm_id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("turbines_pkey");

                    b.ToTable("turbines", (string)null);
                });

            modelBuilder.Entity("server.Models.TurbineAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FarmId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("farm_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("TurbineId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("turbine_id");

                    b.HasKey("Id")
                        .HasName("turbine_alerts_pkey");

                    b.HasIndex("TurbineId");

                    b.ToTable("turbine_alerts", (string)null);
                });

            modelBuilder.Entity("server.Models.TurbineTelemetry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<double?>("AmbientTemperature")
                        .HasColumnType("double precision")
                        .HasColumnName("ambient_temperature");

                    b.Property<double?>("BladePitch")
                        .HasColumnType("double precision")
                        .HasColumnName("blade_pitch");

                    b.Property<string>("FarmId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("farm_id");

                    b.Property<double?>("GearboxTemp")
                        .HasColumnType("double precision")
                        .HasColumnName("gearbox_temp");

                    b.Property<double?>("GeneratorTemp")
                        .HasColumnType("double precision")
                        .HasColumnName("generator_temp");

                    b.Property<double?>("NacelleDirection")
                        .HasColumnType("double precision")
                        .HasColumnName("nacelle_direction");

                    b.Property<double?>("PowerOutput")
                        .HasColumnType("double precision")
                        .HasColumnName("power_output");

                    b.Property<double?>("RotorSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("rotor_speed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'running'::text");

                    b.Property<string>("TurbineId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("turbine_id");

                    b.Property<double?>("Vibration")
                        .HasColumnType("double precision")
                        .HasColumnName("vibration");

                    b.Property<double?>("WindDirection")
                        .HasColumnType("double precision")
                        .HasColumnName("wind_direction");

                    b.Property<double?>("WindSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("wind_speed");

                    b.HasKey("Id", "Timestamp")
                        .HasName("turbine_telemetry_pkey");

                    b.HasIndex(new[] { "TurbineId", "Timestamp" }, "idx_telemetry_turbine_time")
                        .IsDescending(false, true);

                    b.ToTable("turbine_telemetry", (string)null);
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("role")
                        .HasDefaultValueSql("'inspector'::text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("server.Models.OperatorCommand", b =>
                {
                    b.HasOne("server.Models.Turbine", "Turbine")
                        .WithMany("OperatorCommands")
                        .HasForeignKey("TurbineId")
                        .IsRequired()
                        .HasConstraintName("operator_commands_turbine_id_fkey");

                    b.HasOne("server.Models.User", "User")
                        .WithMany("OperatorCommands")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("operator_commands_user_id_fkey");

                    b.Navigation("Turbine");

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.Models.TurbineAlert", b =>
                {
                    b.HasOne("server.Models.Turbine", "Turbine")
                        .WithMany("TurbineAlerts")
                        .HasForeignKey("TurbineId")
                        .IsRequired()
                        .HasConstraintName("turbine_alerts_turbines_id_fk");

                    b.Navigation("Turbine");
                });

            modelBuilder.Entity("server.Models.TurbineTelemetry", b =>
                {
                    b.HasOne("server.Models.Turbine", "Turbine")
                        .WithMany("TurbineTelemetries")
                        .HasForeignKey("TurbineId")
                        .IsRequired()
                        .HasConstraintName("turbine_telemetry_turbines_id_fk");

                    b.Navigation("Turbine");
                });

            modelBuilder.Entity("server.Models.Turbine", b =>
                {
                    b.Navigation("OperatorCommands");

                    b.Navigation("TurbineAlerts");

                    b.Navigation("TurbineTelemetries");
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.Navigation("OperatorCommands");
                });
#pragma warning restore 612, 618
        }
    }
}
